# Generated by Django 5.0.4 on 2024-05-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("description", models.TextField(max_length=250)),
                ("weight", models.IntegerField(default=0)),
                ("geotag_location", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
    ]
